### ISSUE TITLE
Users can continue annotations even if they exceed their assigned tickets

### ISSUE THREAD

**Issue by msharara1998** [vmware/data-annotator-for-machine-learning#348] opened 2022-11-04 16:14 UTC
### Describe the bug

Suppose a user has x tickets to annotate. If he finished x tickets, he can continue labeling normally, which is inconsistent with the logic of sharing the annotation task among many users.

### Reproduction steps

1. Create a project
2. Assign users
3. Login in as an annotator (that has some assigned project)
4. start annotating until exhausting all the assigned tickets.
5. You will see that you can continue normally and annotate data examples that maybe allocated to other users (given that some other users has not completed all his annotations).

### Expected behavior

Each user, upon annotating all his assigned tickets, must see that the submit button is grayed out.

### Additional context

I would be thankful for a detailed description of how to modify the code, and in which specific file, so that the behavior of the application change and conform with the expected behavior mentioned above.

**Comment by lijulia** [comment] 2022-11-07 21:19
@msharara1998, thanks for your feedback.  This is by design not a bug.  By allowing annotators to label more provides more flexibility.  If the assigned tickets per annotator is fixed, it will not be easy for new added annotators to obtain tickets.  It will also block slack channel unknown user’s annotation job.

**Comment by Kai-Qiao** [comment] 2023-06-21 02:46
@msharara1998 Thanks for your feedback, as it's not a bug and it's a special design to help users flexy labeling, so i will close the issue.

**Closed by Kai-Qiao** 2023-06-21 02:46 UTC
Labels: bug
